using UnityEngine;
namespace MantisPunch {
[DefaultExecutionOrder(1000)] public sealed class DuelFinishPresentation:MonoBehaviour {
 MantisDuel duel;bool active;Vector3 cameraStart;Quaternion rotation;float fov;
 void Start(){duel=GetComponent<MantisDuel>();if(System.Array.IndexOf(System.Environment.GetCommandLineArgs(),"-finishTest")>=0)StartCoroutine(Verify());}
 System.Collections.IEnumerator Verify(){
  const string folder="QA/FinishVerified";System.IO.Directory.CreateDirectory(folder);yield return new WaitForSecondsRealtime(2);duel.Restart();var state=typeof(DuelFighter).GetProperty("State");state.SetValue(duel.Enemy,DuelState.Dead);duel.Enemy.presentation.React(CombatBeat.Knockout,duel.Player.transform.forward);yield return new WaitForSecondsRealtime(.7f);ReviewCapture.Save(System.IO.Path.GetFullPath(folder+"/round.png"));bool ok=duel.playerWins==1&&!duel.ShowResult;yield return new WaitForSecondsRealtime(1.1f);ok&=!duel.RoundOver&&duel.ReadyAge>0;
  duel.playerWins=2;state.SetValue(duel.Enemy,DuelState.Dead);duel.Enemy.presentation.React(CombatBeat.Knockout,duel.Player.transform.forward);yield return new WaitForSecondsRealtime(3.5f);ok&=duel.MatchOver&&duel.ShowResult&&duel.playerWins==3;ReviewCapture.Save(System.IO.Path.GetFullPath(folder+"/win.png"));duel.Restart();ok&=duel.playerWins==0&&duel.cpuWins==0&&!duel.RoundOver;Screen.SetResolution(720,1280,FullScreenMode.Windowed);yield return new WaitForSecondsRealtime(.25f);duel.cpuWins=2;state.SetValue(duel.Player,DuelState.Dead);duel.Player.presentation.React(CombatBeat.Knockout,duel.Enemy.transform.forward);yield return new WaitForSecondsRealtime(3.6f);ok&=duel.cpuWins==3&&duel.ShowResult;ReviewCapture.Save(System.IO.Path.GetFullPath(folder+"/lose-portrait.png"),Screen.width,Screen.height);System.IO.File.WriteAllText(folder+"/report.txt",ok?"PASS: auto next round, ready interval, first to 3, victory close-up, restart resets, loss portrait":"FAIL");Application.Quit(ok?0:1);
 }
 void LateUpdate(){if(!duel||!duel.Player||duel.Testing||duel.Hud&&duel.Hud.Paused)return;if(!duel.MatchOver||!duel.RoundOver||duel.ResultAge<.8f){active=false;return;}var winner=duel.Player.Alive?duel.Player:duel.Enemy;var camera=duel.arenaCamera;if(!active){active=true;cameraStart=camera.transform.position;rotation=camera.transform.rotation;fov=camera.fieldOfView;}float age=duel.ResultAge-.8f,t=Mathf.SmoothStep(0,1,Mathf.Clamp01(age/.85f));Vector3 center=winner.transform.position+Vector3.up*.32f,target=center+winner.transform.forward*(BattleLayout.Portrait?3.0f:2.2f)+winner.transform.right*1.0f+Vector3.up*.9f;camera.transform.position=Vector3.Lerp(cameraStart,target,t);camera.transform.rotation=Quaternion.Slerp(rotation,Quaternion.LookRotation(center-target),t);camera.fieldOfView=Mathf.Lerp(fov,43,t);float punch=Mathf.Clamp01((age-.85f)/.85f);winner.visual.Sample(punch>0&&punch<1?punch:.12f,0,Time.time);}
}
}
